import "./globals.css";
import { DM_Sans } from "next/font/google";

const dm_sans = DM_Sans({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="it" dir="ltr">
			<body className={dm_sans.className}>{children}</body>
		</html>
	);
}
